### ISSUE TITLE
[KK]Only 4 first slider work in character editor 

### ISSUE THREAD

**Issue by DidgetMidget** [thojmr/KK_PregnancyPlus#1]
Hey, 

just want to report the the last 6 sliders dosnt look like the change anything in the character creator :D

Thank you for the great mod hope you can fix this issue.

**Comment by thojmr** [comment]
Hey there.  It seems to be working for me with the default characters.  Is it a specific character card?  Can you send me a copy of your output_log after trying to move the broken sliders, and or the character card itself?

**Comment by DidgetMidget** [comment]
Hey i made some tests and yeah its not a special card it dosnt work on deault ones and its not just not showing up in the editor but also not in free h mode. Here is the card i created for testing and the output log i maxed all non working sliders out and nothing changes.

[output_log.txt](https://github.com/thojmr/KK_PregnancyPlus/files/5815586/output_log.txt)

[Koikatu_F_20210114170957711_Haruno Chika_Zero.zip](https://github.com/thojmr/KK_PregnancyPlus/files/5815593/Koikatu_F_20210114170957711_Haruno.Chika_Zero.zip)

reuploaded in a zip i dont know about github nswf stuff

**Comment by thojmr** [comment]
Alright 2 potential solutions.

- Disable "Make me a balloon" plugin config option.  When this is active it disables some sliders.
-  Make sure your Move Z slider is not so far forward that is is outside the characters body.  Since this would then be affecting 0 vertices on the mesh making it look like the sliders are not working.

**Comment by DidgetMidget** [comment]
Yeah it was the "Make me a ballon" option thanks for the help. ^^
