### ISSUE TITLE
[KK] [pregnancyPlus] When changing uncensored type the blendshape will be lost.

### ISSUE THREAD

**Issue by mrxuzhen** [thojmr/KK_PregnancyPlus#11]
I am a timeline scene maker. Most timeline scene maker still works in KK. We mostly rely on pregnancy+ to make the stomach deformation. But most of the times, those chara cards don't have same uncensor type. So when changing chara, the blendshape will be lost and the interpolables in timeline will be deleted either. Is there some way to fix it?

**Comment by thojmr** [comment]
Hey, Preg+ is supposed to automatically swap to the original uncensor when a mismatch is found (It stores the name when originally created).  But its possible there is a bug involved.  Since I'm no longer releasing vanilla KK updates (Only KKS now) This issue will probably not get resolved in KK.

However I just released a new Preg+ [version v7](https://github.com/thojmr/PregnancyPlus/releases) for KKS today that could potentially solve all of your issues with a dedicated timeline slider, that does not require you to make any blendshapes.   Just depends on whether you are willing to make the switch to KKS.

And thanks for the report!

**Comment by mrxuzhen** [comment]
I don't know. To be honest every timeline scene makers are still using KK. The KKS can't support KK scenes. Our timeline maker have been working in KK for years. Once changed, all the work we made will be in vain. That is a hard dicision which is really, really hard to made. I also heard that KKS have more issues than KK. So I am sure that 99% of timeline maker will not switch. It will not feels good when our old works will be in vain.
 If one day, our KK scenes can be ported into KKS, we will not hesitate to switch to KKS. But for now, it is too hard, too hard for everyone who have been working for monthes or years in KK. Too cruel. Well. Thanks for your answer. But I still hope you can help those guys who is not ready to switch.

**Comment by thojmr** [comment]
Yea, some people won't be able to make the switch to KKS yet, but as plugin authors drop support for KK (a few have already) more people will begin to migrate to KKS.  Might take a while though. 
  
In your case the blendshape data will still be saved to the character, but until you switch back to the correct uncensor you will not see it.  As a side note, if the uncenor author updated the uncensor and adds or removes verticies it will no longer be a valid uncensor for the saved blendshape.  It doesn't happen often, but I have seen it happen once.  That's just the way blendshapes work.

For example the "default F" uncensor in KK does not match the "default f" uncensor verts in KKS so scenes will not work when transfered.  However the "sac innie" unccensor is the same between both games, so scenes will work fine from KK -> KKS using that one.  Same goes for clothing.  You just have to be mindful of that.

When it comes down to It, I could update the KK branch alongside KKS, but I just don't have the time to maintain two completely diffferent branches of this plugin that is already nearing 15k lines of code.

**Comment by mrxuzhen** [comment]
Okay I understand. I found that you metioned that when uncensor type were changed back, I checked it carefully, I found the problem now. The P+ is okay, I didn't see bug yet. It is the problem of timeline. When changing uncensor type, The blendshape of O_body_a will be missing for 1 second. You are right, P+ will save the blendshape, but it still take time to write it into blendshape. But when timeline is playing, once it found the object it controls is missing, it will delete the interpolables inmediately. And after that, even p+ write the blendshape back, there will no longer be an interpolable to control the blendshape. That's the goddamn issue.

**Comment by mrxuzhen** [comment]
The timeline have stopped update. Manlymarco was still updating 1.01 1.02 1.03, but there were no any useful new function, but there are more new fucking terrible bugs. I tried to ask him, but he only give me the the github and let me to ask somebody else here. It is him who make timeline 1.01,1.02,1.03 and those new bugs, but he ask me to ask somebody else. Maybe koikatsu will be soon dead. I don't know. There are more and more chara card and timeline authors quitted nowadays, I feels really sad.

**Comment by thojmr** [comment]
I decided to do one last KK update to include a bunch of bugfixes, but will also include the new Timeline interpolable.  So once it's out (soon) you can start using that instead of the BlendShape GUI.  

So you can now make timeline scenes in KK that port to KKS safely.  And no longer have to worry about meshes and uncensors.  The downside is older scnes will still depend on the BlendShape GUI like they have, until you manually update them to  use the new interpolable in timeline.

**Comment by mrxuzhen** [comment]
Thank you very much. I have one last question that is there some tools to port kk scenes into kks? I remember when I load kk charater card in kks it will be ported automatically. But when I tried to load kk scenes in kks studio it only shows that there are no scene data. Do such a tool exsist?

**Comment by thojmr** [comment]
It should happen automatically.  Not sure if it works with drag and drop.  And it probably depends on what other plugins you are using in your scenes.  There are no external tools that I know of.
